### ISSUE TITLE
Coerce doesn't work in cljs

### ISSUE THREAD

**Issue by khmelevskii** [wilkerlucio/spec-coerce#8] opened 2018-09-20 11:32 UTC
Hello,
I have problems with this lib:

```
(ns test.foo
  (:require [spec-coerce.core :as sc]))

(sc/coerce `int? "10") => "10"
```

my dependencies
```
 :deps
 {reagent        {:mvn/version "0.8.1"}
  re-frame       {:mvn/version "0.10.6"}
  metosin/reitit {:mvn/version "0.2.2"}
  spec-coerce    {:mvn/version "1.0.0-alpha6"}}
```

how I can debug problem?

**Comment by wilkerlucio** [comment] 2018-09-20 16:33
I just tried in a project with the CLJS and I can't reproduce the issue, which version of clojurescript are you using? and what are you using to compile it?

**Comment by khmelevskii** [comment] 2018-09-20 18:37
@wilkerlucio I'm using latest clojurescript and shadow-cljs. I will try to create small repo with this problem tomorrow

**Comment by wilkerlucio** [comment] 2018-09-20 18:45
@khmelevskii I'm not using latest cljs, I guess something about spec inference could have changed since, a repo will be nice to debug, thanks.

**Comment by wilkerlucio** [comment] 2018-11-16 11:20
@khmelevskii I wasn't able to reproduce it. Are you still having this issue?

**Comment by wilkerlucio** [comment] 2019-02-05 15:23
Closing for now, please re-open if that still an issue.

**Closed by wilkerlucio** 2019-02-05 15:23 UTC
